defmodule ExMachine.Server do
  @moduledoc """
  GenServer wrapper that turns a statechart module into a long-lived
  process you can `cast` and `call` events at.

  ## Quick start

      defmodule TrafficLight do
        use ExMachine.Statechart

        initial :red
        state :red,    do: on(:timer, target: :green)
        state :green,  do: on(:timer, target: :yellow)
        state :yellow, do: on(:timer, target: :red)
      end

      defmodule TrafficLight.Server do
        use ExMachine.Server, statechart: TrafficLight
      end

      {:ok, pid} = TrafficLight.Server.start_link(name: :tl)
      :ok = TrafficLight.Server.send_event(:tl, :timer)
      {:ok, snap} = TrafficLight.Server.call_event(:tl, :timer)
      snap.atomic_states  # => [:yellow]

  ## API surface

  Generated by `use ExMachine.Server`:

    * `start_link/1` — accepts `[name: term, context: term]`. `:context`
      overrides the statechart's `initial_context`. Any other key is
      passed straight to `GenServer.start_link/3` as a server option.
    * `send_event/2` and `send_event/3` — fire-and-forget cast.
    * `call_event/2` and `call_event/3` — synchronous; replies with
      `{:ok, %Snapshot{}}` or `{:error, :not_running}`.
    * `get_configuration/1`, `get_context/1`, `get_snapshot/1` — sync.
    * `subscribe/1` and `unsubscribe/1` — register the calling process
      to receive `{:ex_machine, :transition, %Snapshot{}}` after every
      macrostep and `{:ex_machine, :stopped, reason}` once the machine
      reaches a terminal configuration.
    * `stop/1`, `stop/2`, `stop/3` — `GenServer.stop/3` passthrough.

  ## Lifecycle

  When the machine reaches a terminal configuration (top-level `:final`
  or every region of a parallel root done), the GenServer **does not
  terminate**. It stays alive so subscribers can still query the final
  snapshot, but refuses further events: `send_event/2` is silently
  dropped, `call_event/2` returns `{:error, :not_running}`. Use `stop/1`
  to terminate the process explicitly.
  """

  use GenServer

  alias ExMachine.{Engine, Machine, Snapshot, Telemetry}

  @pubsub ExMachine.PubSub

  # ── __using__ ────────────────────────────────────────────────────────────

  @doc false
  defmacro __using__(opts) do
    statechart = Keyword.fetch!(opts, :statechart)

    quote do
      @statechart unquote(statechart)

      def child_spec(args) do
        ExMachine.Server.child_spec({@statechart, args})
      end

      def start_link(args \\ []),
        do: ExMachine.Server.start_link(@statechart, args)

      def send_event(server, event, params \\ nil),
        do: ExMachine.Server.send_event(server, event, params)

      def call_event(server, event, params \\ nil, timeout \\ 5000),
        do: ExMachine.Server.call_event(server, event, params, timeout)

      def get_configuration(server),
        do: ExMachine.Server.get_configuration(server)

      def get_context(server),
        do: ExMachine.Server.get_context(server)

      def get_snapshot(server),
        do: ExMachine.Server.get_snapshot(server)

      def subscribe(server),
        do: ExMachine.Server.subscribe(server)

      def unsubscribe(server),
        do: ExMachine.Server.unsubscribe(server)

      def stop(server, reason \\ :normal, timeout \\ :infinity),
        do: ExMachine.Server.stop(server, reason, timeout)
    end
  end

  # ── child_spec for direct use ────────────────────────────────────────────

  @doc false
  def child_spec({statechart, args}) do
    %{
      id: Keyword.get(args, :name, statechart),
      start: {__MODULE__, :start_link, [statechart, args]},
      type: :worker,
      restart: :transient
    }
  end

  # ── Public API ───────────────────────────────────────────────────────────

  @doc """
  Start a server backed by the given statechart module. Recognised
  args: `:name`, `:context`. All other args are forwarded to
  `GenServer.start_link/3` as server options.
  """
  @spec start_link(module(), keyword()) :: GenServer.on_start()
  def start_link(statechart, args) when is_atom(statechart) and is_list(args) do
    {gen_opts, init_args} = Keyword.split(args, [:name])
    GenServer.start_link(__MODULE__, {statechart, init_args}, gen_opts)
  end

  @doc "Cast an event to the server. Returns `:ok` immediately."
  @spec send_event(GenServer.server(), term(), term()) :: :ok
  def send_event(server, event, params \\ nil) do
    GenServer.cast(server, {:event, event, params})
  end

  @doc """
  Synchronously dispatch an event and wait for the resulting snapshot.
  Returns `{:ok, %Snapshot{}}` on success, `{:error, :not_running}` if
  the machine has already stopped.
  """
  @spec call_event(GenServer.server(), term(), term(), timeout()) ::
          {:ok, Snapshot.t()} | {:error, :not_running}
  def call_event(server, event, params \\ nil, timeout \\ 5000) do
    GenServer.call(server, {:event, event, params}, timeout)
  end

  @doc "Return the current `MapSet` of active state ids."
  @spec get_configuration(GenServer.server()) :: MapSet.t(atom())
  def get_configuration(server), do: GenServer.call(server, :get_configuration)

  @doc "Return the current user context."
  @spec get_context(GenServer.server()) :: term()
  def get_context(server), do: GenServer.call(server, :get_context)

  @doc "Return the current `%Snapshot{}`."
  @spec get_snapshot(GenServer.server()) :: Snapshot.t()
  def get_snapshot(server), do: GenServer.call(server, :get_snapshot)

  @doc """
  Register the calling process for transition + stopped notifications.

  Each call adds a fresh registration; the dispatch path filters
  duplicates so a subscriber that registers twice still receives one
  message per event. Use `unsubscribe/1` to drop all of the calling
  process's registrations for `server`.
  """
  @spec subscribe(GenServer.server()) :: :ok
  def subscribe(server) do
    pid = resolve_pid!(server)
    {:ok, _} = Registry.register(@pubsub, pid, nil)
    :ok
  end

  @doc "Stop receiving notifications for `server`."
  @spec unsubscribe(GenServer.server()) :: :ok
  def unsubscribe(server) do
    pid = resolve_pid!(server)
    Registry.unregister(@pubsub, pid)
    :ok
  end

  @doc "Stop the server. See `GenServer.stop/3`."
  @spec stop(GenServer.server(), term(), timeout()) :: :ok
  def stop(server, reason \\ :normal, timeout \\ :infinity) do
    GenServer.stop(server, reason, timeout)
  end

  defp resolve_pid!(pid) when is_pid(pid), do: pid

  defp resolve_pid!(server) do
    case GenServer.whereis(server) do
      pid when is_pid(pid) -> pid
      nil -> raise ArgumentError, "no process registered for #{inspect(server)}"
    end
  end

  # ── GenServer callbacks ──────────────────────────────────────────────────

  @impl true
  def init({statechart, args}) do
    context = Keyword.get(args, :context)
    machine = ExMachine.init(statechart, context)
    publish_transition(self(), Snapshot.from_machine(machine))
    maybe_publish_stopped(self(), machine)
    {:ok, machine}
  end

  @impl true
  def handle_cast({:event, _event, _params}, %Machine{running?: false} = machine) do
    {:noreply, machine}
  end

  def handle_cast({:event, event, params}, %Machine{} = machine) do
    {:noreply, dispatch_and_publish(machine, event, params)}
  end

  @impl true
  def handle_call({:event, _event, _params}, _from, %Machine{running?: false} = machine) do
    {:reply, {:error, :not_running}, machine}
  end

  def handle_call({:event, event, params}, _from, %Machine{} = machine) do
    new_machine = dispatch_and_publish(machine, event, params)
    {:reply, {:ok, Snapshot.from_machine(new_machine)}, new_machine}
  end

  def handle_call(:get_configuration, _from, machine),
    do: {:reply, machine.configuration, machine}

  def handle_call(:get_context, _from, machine), do: {:reply, machine.context, machine}

  def handle_call(:get_snapshot, _from, machine),
    do: {:reply, Snapshot.from_machine(machine), machine}

  # ── Internal ─────────────────────────────────────────────────────────────

  defp dispatch_and_publish(%Machine{} = machine, event, params) do
    payload = build_event(event, params)
    server = self()
    metadata = %{server: server, event: payload}

    new_machine =
      Telemetry.macrostep(metadata, fn ->
        Engine.dispatch(machine, payload)
      end)

    snapshot = Snapshot.from_machine(new_machine)
    publish_transition(server, snapshot)
    maybe_publish_stopped(server, new_machine)
    new_machine
  end

  defp build_event(event, nil), do: event
  defp build_event(event, params), do: {event, params}

  defp publish_transition(server, %Snapshot{} = snapshot) do
    broadcast(server, {:ex_machine, :transition, snapshot})
  end

  defp maybe_publish_stopped(_server, %Machine{running?: true}), do: :ok

  defp maybe_publish_stopped(server, %Machine{} = machine) do
    snapshot = Snapshot.from_machine(machine)
    Telemetry.stopped(server, :normal, snapshot)
    broadcast(server, {:ex_machine, :stopped, :normal})
  end

  defp broadcast(server, message) do
    Registry.dispatch(@pubsub, server, fn entries ->
      entries
      |> Enum.map(fn {sub_pid, _} -> sub_pid end)
      |> Enum.uniq()
      |> Enum.each(fn pid -> send(pid, message) end)
    end)
  end
end
