defmodule ExMachine.Server do
  @moduledoc """
  GenServer wrapper that turns a statechart module into a long-lived
  process you can `cast` and `call` events at.

  ## Quick start

      defmodule TrafficLight do
        use ExMachine.Statechart

        initial :red
        state :red,    do: on(:timer, target: :green)
        state :green,  do: on(:timer, target: :yellow)
        state :yellow, do: on(:timer, target: :red)
      end

      defmodule TrafficLight.Server do
        use ExMachine.Server, statechart: TrafficLight
      end

      {:ok, pid} = TrafficLight.Server.start_link(name: :tl)
      :ok = TrafficLight.Server.send_event(:tl, :timer)
      {:ok, snap} = TrafficLight.Server.call_event(:tl, :timer)
      snap.atomic_states  # => [:yellow]

  ## API surface

  Generated by `use ExMachine.Server`:

    * `start_link/1` — accepts `[name: term, context: term]`. `:context`
      overrides the statechart's `initial_context`. Any other key is
      passed straight to `GenServer.start_link/3` as a server option.
    * `send_event/2` and `send_event/3` — fire-and-forget cast.
    * `call_event/2` and `call_event/3` — synchronous; replies with
      `{:ok, %Snapshot{}}` or `{:error, :not_running}`.
    * `get_configuration/1`, `get_context/1`, `get_snapshot/1` — sync.
    * `subscribe/1` and `unsubscribe/1` — register the calling process
      to receive `{:ex_machine, :transition, %Snapshot{}}` after every
      macrostep and `{:ex_machine, :stopped, reason}` once the machine
      reaches a terminal configuration.
    * `stop/1`, `stop/2`, `stop/3` — `GenServer.stop/3` passthrough.

  ## Lifecycle

  When the machine reaches a terminal configuration (top-level `:final`
  or every region of a parallel root done), the GenServer **does not
  terminate**. It stays alive so subscribers can still query the final
  snapshot, but refuses further events: `send_event/2` is silently
  dropped, `call_event/2` returns `{:error, :not_running}`. Use `stop/1`
  to terminate the process explicitly.

  ## Delayed events and invoked services (M7)

  Actions can request side effects via the `ExMachine.Step` helpers:

    * `Step.send_after(step, event, ms, owner_state)` schedules `event`
      to be re-dispatched to this server after `ms` milliseconds. The
      timer is cancelled automatically when `owner_state` is exited or
      when the returned ref is passed to `Step.cancel/2`.
    * `Step.invoke(step, id, fun_or_mfa, owner_state)` spawns the
      function under a per-server `Task.Supervisor`. On success the
      server raises `done.invoke.<id>` with the function's return value
      as event params; on failure, `error.invoke.<id>` with the crash
      reason. The task is killed when `owner_state` is exited or when
      `id` is passed to `Step.cancel/2`. Use a stable atom for `id` so
      the DSL can declare a transition that listens for the event.

  Both are honoured ONLY in server-mode; pure callers of
  `ExMachine.dispatch/2` see the requests in
  `machine.pending_delayed` / `pending_invokes` and may inspect or
  ignore them.
  """

  use GenServer

  alias ExMachine.{Engine, Machine, Snapshot, Telemetry}

  @pubsub ExMachine.PubSub

  defmodule State do
    @moduledoc false
    # Runtime state of an ExMachine.Server process.
    defstruct [
      :machine,
      :task_supervisor,
      timers: %{},
      invocations: %{}
    ]
  end

  # ── __using__ ────────────────────────────────────────────────────────────

  @doc false
  defmacro __using__(opts) do
    statechart = Keyword.fetch!(opts, :statechart)

    quote do
      @statechart unquote(statechart)

      def child_spec(args) do
        ExMachine.Server.child_spec({@statechart, args})
      end

      def start_link(args \\ []),
        do: ExMachine.Server.start_link(@statechart, args)

      def send_event(server, event, params \\ nil),
        do: ExMachine.Server.send_event(server, event, params)

      def call_event(server, event, params \\ nil, timeout \\ 5000),
        do: ExMachine.Server.call_event(server, event, params, timeout)

      def get_configuration(server),
        do: ExMachine.Server.get_configuration(server)

      def get_context(server),
        do: ExMachine.Server.get_context(server)

      def get_snapshot(server),
        do: ExMachine.Server.get_snapshot(server)

      def subscribe(server),
        do: ExMachine.Server.subscribe(server)

      def unsubscribe(server),
        do: ExMachine.Server.unsubscribe(server)

      def stop(server, reason \\ :normal, timeout \\ :infinity),
        do: ExMachine.Server.stop(server, reason, timeout)
    end
  end

  # ── child_spec for direct use ────────────────────────────────────────────

  @doc false
  def child_spec({statechart, args}) do
    %{
      id: Keyword.get(args, :name, statechart),
      start: {__MODULE__, :start_link, [statechart, args]},
      type: :worker,
      restart: :transient
    }
  end

  # ── Public API ───────────────────────────────────────────────────────────

  @doc """
  Start a server backed by the given statechart module. Recognised
  args: `:name`, `:context`. All other args are forwarded to
  `GenServer.start_link/3` as server options.
  """
  @spec start_link(module(), keyword()) :: GenServer.on_start()
  def start_link(statechart, args) when is_atom(statechart) and is_list(args) do
    {gen_opts, init_args} = Keyword.split(args, [:name])
    GenServer.start_link(__MODULE__, {statechart, init_args}, gen_opts)
  end

  @doc "Cast an event to the server. Returns `:ok` immediately."
  @spec send_event(GenServer.server(), term(), term()) :: :ok
  def send_event(server, event, params \\ nil) do
    GenServer.cast(server, {:event, event, params})
  end

  @doc """
  Synchronously dispatch an event and wait for the resulting snapshot.
  Returns `{:ok, %Snapshot{}}` on success, `{:error, :not_running}` if
  the machine has already stopped.
  """
  @spec call_event(GenServer.server(), term(), term(), timeout()) ::
          {:ok, Snapshot.t()} | {:error, :not_running}
  def call_event(server, event, params \\ nil, timeout \\ 5000) do
    GenServer.call(server, {:event, event, params}, timeout)
  end

  @doc "Return the current `MapSet` of active state ids."
  @spec get_configuration(GenServer.server()) :: MapSet.t(atom())
  def get_configuration(server), do: GenServer.call(server, :get_configuration)

  @doc "Return the current user context."
  @spec get_context(GenServer.server()) :: term()
  def get_context(server), do: GenServer.call(server, :get_context)

  @doc "Return the current `%Snapshot{}`."
  @spec get_snapshot(GenServer.server()) :: Snapshot.t()
  def get_snapshot(server), do: GenServer.call(server, :get_snapshot)

  @doc """
  Register the calling process for transition + stopped notifications.

  Each call adds a fresh registration; the dispatch path filters
  duplicates so a subscriber that registers twice still receives one
  message per event. Use `unsubscribe/1` to drop all of the calling
  process's registrations for `server`.
  """
  @spec subscribe(GenServer.server()) :: :ok
  def subscribe(server) do
    pid = resolve_pid!(server)
    {:ok, _} = Registry.register(@pubsub, pid, nil)
    :ok
  end

  @doc "Stop receiving notifications for `server`."
  @spec unsubscribe(GenServer.server()) :: :ok
  def unsubscribe(server) do
    pid = resolve_pid!(server)
    Registry.unregister(@pubsub, pid)
    :ok
  end

  @doc "Stop the server. See `GenServer.stop/3`."
  @spec stop(GenServer.server(), term(), timeout()) :: :ok
  def stop(server, reason \\ :normal, timeout \\ :infinity) do
    GenServer.stop(server, reason, timeout)
  end

  defp resolve_pid!(pid) when is_pid(pid), do: pid

  defp resolve_pid!(server) do
    case GenServer.whereis(server) do
      pid when is_pid(pid) -> pid
      nil -> raise ArgumentError, "no process registered for #{inspect(server)}"
    end
  end

  # ── GenServer callbacks ──────────────────────────────────────────────────

  @impl true
  def init({statechart, args}) do
    Process.flag(:trap_exit, true)
    context = Keyword.get(args, :context)
    {:ok, supervisor} = Task.Supervisor.start_link()
    machine = ExMachine.init(statechart, context)

    state = %State{machine: machine, task_supervisor: supervisor}
    state = process_side_effects(state, machine)

    publish_transition(self(), Snapshot.from_machine(machine))
    maybe_publish_stopped(self(), machine)
    {:ok, state}
  end

  @impl true
  def handle_cast({:event, _event, _params}, %State{machine: %Machine{running?: false}} = state) do
    {:noreply, state}
  end

  def handle_cast({:event, event, params}, %State{} = state) do
    {:noreply, internal_dispatch(state, build_event(event, params))}
  end

  @impl true
  def handle_call(
        {:event, _event, _params},
        _from,
        %State{machine: %Machine{running?: false}} = s
      ) do
    {:reply, {:error, :not_running}, s}
  end

  def handle_call({:event, event, params}, _from, %State{} = state) do
    new_state = internal_dispatch(state, build_event(event, params))
    {:reply, {:ok, Snapshot.from_machine(new_state.machine)}, new_state}
  end

  def handle_call(:get_configuration, _from, %State{machine: m} = s),
    do: {:reply, m.configuration, s}

  def handle_call(:get_context, _from, %State{machine: m} = s), do: {:reply, m.context, s}

  def handle_call(:get_snapshot, _from, %State{machine: m} = s),
    do: {:reply, Snapshot.from_machine(m), s}

  # ── handle_info: timers and tasks ────────────────────────────────────────

  @impl true
  def handle_info({:ex_machine_timer, ref, event}, %State{} = state) do
    case Map.pop(state.timers, ref) do
      {nil, _} ->
        {:noreply, state}

      {_entry, timers} ->
        state = %{state | timers: timers}

        if state.machine.running? do
          {:noreply, internal_dispatch(state, event)}
        else
          {:noreply, state}
        end
    end
  end

  def handle_info({task_ref, result}, %State{} = state) when is_reference(task_ref) do
    case Map.pop(state.invocations, task_ref) do
      {nil, _} ->
        {:noreply, state}

      {{id, _owner, _pid}, invocations} ->
        Process.demonitor(task_ref, [:flush])
        state = %{state | invocations: invocations}

        if state.machine.running? do
          {:noreply, internal_dispatch(state, {invoke_done_event(id), result})}
        else
          {:noreply, state}
        end
    end
  end

  def handle_info({:DOWN, ref, :process, _pid, reason}, %State{} = state)
      when is_reference(ref) do
    case Map.pop(state.invocations, ref) do
      {nil, _} ->
        {:noreply, state}

      {{id, _owner, _pid}, invocations} ->
        state = %{state | invocations: invocations}

        if state.machine.running? do
          {:noreply, internal_dispatch(state, {invoke_error_event(id), reason})}
        else
          {:noreply, state}
        end
    end
  end

  def handle_info(_, state), do: {:noreply, state}

  @impl true
  def terminate(_reason, %State{} = state) do
    cancel_all_timers(state)
    :ok
  end

  # ── Internal dispatch + side effects ─────────────────────────────────────

  defp internal_dispatch(%State{} = state, event) do
    server = self()
    metadata = %{server: server, event: event}

    new_machine =
      Telemetry.macrostep(metadata, fn ->
        Engine.dispatch(state.machine, event)
      end)

    state = %{state | machine: new_machine}
    state = process_side_effects(state, new_machine)

    publish_transition(server, Snapshot.from_machine(new_machine))
    maybe_publish_stopped(server, new_machine)
    state
  end

  # Apply the side-effect requests (delayed events, invocations,
  # cancellations) accumulated during the most recent init/dispatch, plus
  # auto-cancel any timer/task whose owner state was exited.
  defp process_side_effects(%State{} = state, %Machine{} = machine) do
    state
    |> apply_explicit_cancels(machine.pending_cancels)
    |> auto_cancel_on_exit(machine.trace)
    |> schedule_delayed(machine.pending_delayed)
    |> spawn_invocations(machine.pending_invokes)
  end

  defp apply_explicit_cancels(%State{} = state, []), do: state

  defp apply_explicit_cancels(%State{} = state, keys) do
    keys = MapSet.new(keys)

    state
    |> drop_timers(fn ref -> MapSet.member?(keys, ref) end)
    |> drop_invocations(fn id -> MapSet.member?(keys, id) end)
  end

  defp auto_cancel_on_exit(%State{} = state, %{exited: []}), do: state

  defp auto_cancel_on_exit(%State{} = state, %{exited: exited}) do
    exited_set = MapSet.new(exited)

    state
    |> drop_timers(fn _ref -> false end, exited_set)
    |> drop_invocations(fn _ref -> false end, exited_set)
  end

  defp drop_timers(state, ref_pred, owner_set \\ MapSet.new()) do
    {to_drop, to_keep} =
      Enum.split_with(state.timers, fn {ref, {_timer_ref, owner, _ev}} ->
        ref_pred.(ref) or MapSet.member?(owner_set, owner)
      end)

    Enum.each(to_drop, fn {_ref, {timer_ref, _o, _e}} -> Process.cancel_timer(timer_ref) end)
    %{state | timers: Map.new(to_keep)}
  end

  defp drop_invocations(state, id_pred, owner_set \\ MapSet.new()) do
    {to_drop, to_keep} =
      Enum.split_with(state.invocations, fn {_task_ref, {id, owner, _pid}} ->
        id_pred.(id) or MapSet.member?(owner_set, owner)
      end)

    Enum.each(to_drop, fn {task_ref, {_id, _owner, pid}} ->
      Process.demonitor(task_ref, [:flush])
      Process.exit(pid, :kill)
    end)

    %{state | invocations: Map.new(to_keep)}
  end

  defp schedule_delayed(%State{} = state, []), do: state

  defp schedule_delayed(%State{} = state, entries) do
    Enum.reduce(entries, state, fn {ref, event, ms, owner}, acc ->
      timer_ref = Process.send_after(self(), {:ex_machine_timer, ref, event}, ms)
      %{acc | timers: Map.put(acc.timers, ref, {timer_ref, owner, event})}
    end)
  end

  defp spawn_invocations(%State{} = state, []), do: state

  defp spawn_invocations(%State{} = state, entries) do
    Enum.reduce(entries, state, fn {id, spec, owner}, acc ->
      task = Task.Supervisor.async_nolink(acc.task_supervisor, fn -> run_invoke(spec) end)
      %{acc | invocations: Map.put(acc.invocations, task.ref, {id, owner, task.pid})}
    end)
  end

  defp run_invoke({m, f, a}) when is_atom(m) and is_atom(f) and is_list(a), do: apply(m, f, a)
  defp run_invoke(fun) when is_function(fun, 0), do: fun.()

  defp cancel_all_timers(%State{timers: timers}) do
    Enum.each(timers, fn {_ref, {timer_ref, _o, _e}} -> Process.cancel_timer(timer_ref) end)
  end

  defp invoke_done_event(id) when is_atom(id) do
    String.to_atom("done.invoke." <> Atom.to_string(id))
  end

  defp invoke_error_event(id) when is_atom(id) do
    String.to_atom("error.invoke." <> Atom.to_string(id))
  end

  defp build_event(event, nil), do: event
  defp build_event(event, params), do: {event, params}

  defp publish_transition(server, %Snapshot{} = snapshot) do
    broadcast(server, {:ex_machine, :transition, snapshot})
  end

  defp maybe_publish_stopped(_server, %Machine{running?: true}), do: :ok

  defp maybe_publish_stopped(server, %Machine{} = machine) do
    snapshot = Snapshot.from_machine(machine)
    Telemetry.stopped(server, :normal, snapshot)
    broadcast(server, {:ex_machine, :stopped, :normal})
  end

  defp broadcast(server, message) do
    Registry.dispatch(@pubsub, server, fn entries ->
      entries
      |> Enum.map(fn {sub_pid, _} -> sub_pid end)
      |> Enum.uniq()
      |> Enum.each(fn pid -> send(pid, message) end)
    end)
  end
end
